### ISSUE TITLE
Something broken with the United Kingdom "recovered" numbers

### ISSUE THREAD

**Issue by ewildgoose** [code-shoily/covid19#12]
Beautiful and incredible app!

The numbers of recovered look wrong on a few countries, for example the United Kingdom. Not checked the code, but I wonder if its related to fixups concerning region names or aggregations of country states to dependent countries, eg there are zero recovered in England, but UK shows the recovered as the sum of the remaining countries which do have numbers within that region?

**Comment by code-shoily** [comment]
Thank you for pointing out, I will look into the data, there was something similar with data in Canada too.
